// DOM/voice/network simulations, deliberately not a physical microphone test.
const {JSDOM}=require('jsdom'),fs=require('fs'),assert=require('assert/strict'),path=require('path');
const root=path.resolve(__dirname,'..'),source=fs.readFileSync(process.env.AUDIT_APP_JS||root+'/static/app.js','utf8');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const wait=async(fn,limit=2000)=>{const end=Date.now()+limit;while(Date.now()<end){if(fn())return;await sleep(20);}throw Error('Condition non atteinte');};
const p=(name,code)=>({name,code,id:code,keywords:'',image:'',note:'',demo:false});
const result=(name,code)=>({products:[p(name,code)],answers:[],revision:'r1'});
function page(handler){
 const dom=new JSDOM(fs.readFileSync(root+'/templates/index.html','utf8'),{url:'https://caisse.test/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;
 w.AbortController=AbortController;w.setInterval=fn=>{w.pollTest=fn;return 1};w.clearInterval=()=>{};
 w.fetch=async(url,options={})=>{
  let data;
  if(url==='/api/session')data={kiosk_required:false};
  else if(url==='/api/revision')data={revision:'r1'};
  else data=await handler(url,options);
  return {ok:true,status:200,json:async()=>data};
 };
 Object.defineProperty(w,'isSecureContext',{value:true});
 w.SpeechRecognition=class{constructor(){w.speech=this}start(){this.onstart?.()}stop(){}abort(){this.onend?.()}};
 w.eval(source);return dom;
}
function query(dom,text){const w=dom.window,e=w.document.querySelector('#query');e.value=text;e.dispatchEvent(new w.Event('input',{bubbles:true}));w.document.querySelector('#search-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));}
const standard=async(url,o)=>url==='/api/catalog'?{products:[p('Accueil','HOME')],demo_count:0,revision:'r1'}:result(JSON.parse(o.body).query,JSON.parse(o.body).query);
const results=[];
async function test(name,fn){try{await fn();results.push({name,ok:true});}catch(e){results.push({name,ok:false,error:e.message});}}
(async()=>{
 await test('ancien accueil lent ne remplace pas la nouvelle recherche',async()=>{let release;const dom=page(async(url,o)=>url==='/api/catalog'?new Promise(r=>release=r):standard(url,o));try{await wait(()=>release);query(dom,'BANANE');await wait(()=>dom.window.document.querySelector('.plu')?.textContent==='BANANE');release({products:[p('Accueil','HOME')],demo_count:0,revision:'r1'});await sleep(80);assert.equal(dom.window.document.querySelector('.plu')?.textContent,'BANANE');}finally{dom.window.close();}});
 await test('ancien code masque immédiatement pendant une recherche lente',async()=>{let release;const dom=page(async(url,o)=>url==='/api/search'?new Promise(r=>release=r):standard(url,o));try{await wait(()=>dom.window.document.querySelector('.plu'));query(dom,'NOUVEAU');assert.equal(dom.window.document.querySelector('.plu'),null);assert.equal(dom.window.document.querySelector('#results').getAttribute('aria-busy'),'true');await wait(()=>release);release(result('Nouveau','NEW'));await wait(()=>dom.window.document.querySelector('.plu')?.textContent==='NEW');}finally{dom.window.close();}});
 await test('dépassement réel du délai de 12 secondes puis nouvelle tentative',async()=>{let retry=false;const dom=page(async(url,o)=>{if(url==='/api/search'&&!retry)return new Promise((resolve,reject)=>o.signal.addEventListener('abort',()=>reject(Object.assign(new Error('aborted'),{name:'AbortError'})),{once:true}));return standard(url,o)});try{await wait(()=>dom.window.document.querySelector('.plu'));const start=Date.now();query(dom,'GALA');await wait(()=>dom.window.document.querySelector('[data-retry]'),13500);assert(Date.now()-start>=11900);assert.equal(dom.window.document.querySelector('#query').value,'GALA');retry=true;dom.window.document.querySelector('[data-retry]').click();await wait(()=>dom.window.document.querySelector('.plu')?.textContent==='GALA');}finally{dom.window.close();}});
 await test('coupure réseau provoquée, texte conservé, reprise',async()=>{const dom=page(standard);try{await wait(()=>dom.window.document.querySelector('.plu'));query(dom,'BROCOLI');await wait(()=>dom.window.document.querySelector('.plu')?.textContent==='BROCOLI');dom.window.dispatchEvent(new dom.window.Event('offline'));assert.equal(dom.window.document.querySelector('.plu'),null);assert.equal(dom.window.document.querySelector('#query').value,'BROCOLI');dom.window.dispatchEvent(new dom.window.Event('online'));await wait(()=>dom.window.document.querySelector('.plu')?.textContent==='BROCOLI');}finally{dom.window.close();}});
 await test('trois vues simultanées sans mélange',async()=>{const pages=[page(standard),page(standard),page(standard)];try{await Promise.all(pages.map(async(d,i)=>{await wait(()=>d.window.document.querySelector('.plu'));query(d,['POMME','BANANE','BROCOLI'][i]);await wait(()=>d.window.document.querySelector('.plu')?.textContent===['POMME','BANANE','BROCOLI'][i]);}));assert.deepEqual(pages.map(d=>d.window.document.querySelector('.plu').textContent),['POMME','BANANE','BROCOLI']);}finally{pages.forEach(d=>d.window.close());}});
 await test('micro simulé : refus, silence, indisponibilité, correction clavier et demandes successives',async()=>{const dom=page(standard),w=dom.window;try{await wait(()=>w.document.querySelector('.plu'));for(const error of ['not-allowed','no-speech','audio-capture','network']){w.document.querySelector('#mic').click();w.speech.onerror({error});assert(!w.document.querySelector('#mic').classList.contains('listening'));assert(w.document.querySelector('#voice-status').textContent.length>20);}w.document.querySelector('#mic').click();query(dom,'CORRECTION');await wait(()=>w.document.querySelector('.plu')?.textContent==='CORRECTION');const speech=[{transcript:'ANCIEN'}];speech.isFinal=true;w.speech.onresult({resultIndex:0,results:[speech]});await sleep(50);assert.equal(w.document.querySelector('#query').value,'CORRECTION');for(const text of ['GALA','GINGEMBRE']){w.document.querySelector('#mic').click();const r=[{transcript:text}];r.isFinal=true;w.speech.onresult({resultIndex:0,results:[r]});await wait(()=>w.document.querySelector('.plu')?.textContent===text);}}finally{w.close();}});
 await test('micro simulé bloqué interrompu après 15 secondes réelles',async()=>{const dom=page(standard),w=dom.window;try{await wait(()=>w.document.querySelector('.plu'));w.document.querySelector('#mic').click();await wait(()=>!w.document.querySelector('#mic').classList.contains('listening'),16500);assert(w.document.querySelector('#voice-status').textContent.includes('15 secondes'));}finally{w.close();}});
 await test('image absente ou cassée laisse le code accessible',async()=>{const dom=page(async(url,o)=>url==='/api/search'?{products:[{...p('Produit','123'),image:'/bad.jpg'}],revision:'r1'}:standard(url,o));try{await wait(()=>dom.window.document.querySelector('.plu'));assert.equal(dom.window.document.querySelector('.plu').textContent,'HOME');assert(dom.window.document.querySelector('.placeholder'));query(dom,'123');await wait(()=>dom.window.document.querySelector('#results img'));dom.window.document.querySelector('#results img').dispatchEvent(new dom.window.Event('error'));assert.equal(dom.window.document.querySelector('.plu').textContent,'123');assert(dom.window.document.querySelector('.placeholder').textContent.includes('indisponible'));}finally{dom.window.close();}});
 await test('démarrage du micro annulé puis événements tardifs ignorés',async()=>{const dom=page(standard),w=dom.window;try{await wait(()=>w.document.querySelector('.plu'));w.SpeechRecognition.prototype.start=function(){};const mic=w.document.querySelector('#mic');mic.click();const old=w.speech;assert.equal(mic.getAttribute('aria-pressed'),'true');mic.click();old.onstart();assert.equal(mic.getAttribute('aria-pressed'),'false');mic.click();const current=w.speech;current.onstart();old.onend();assert(mic.classList.contains('listening'));mic.click();}finally{w.close();}});
 await test('micro sans réponse libéré après huit secondes',async()=>{const dom=page(standard),w=dom.window;try{await wait(()=>w.document.querySelector('.plu'));w.SpeechRecognition.prototype.start=function(){};w.document.querySelector('#mic').click();await wait(()=>w.document.querySelector('#voice-status').textContent.includes('ne démarre pas'),9000);assert.equal(w.document.querySelector('#mic').getAttribute('aria-pressed'),'false');}finally{w.close();}});
 console.log(JSON.stringify(results,null,2));if(process.env.AUDIT_FAULT_OUTPUT)fs.writeFileSync(process.env.AUDIT_FAULT_OUTPUT,JSON.stringify(results,null,2));if(results.some(r=>!r.ok))process.exitCode=1;
})();
