const assert=require('node:assert/strict');
const fs=require('node:fs');
const {JSDOM}=require('jsdom');
const dom=new JSDOM(fs.readFileSync('templates/photo_trial.html','utf8'),{runScripts:'outside-only',url:'https://example.test/essai-photo'});
const w=dom.window, images=[], revoked=[], blobs=[];
let network=0, next=0;
w.fetch=()=>{network++;throw Error('No network permitted');};
w.URL.createObjectURL=()=>`blob:test-${++next}`;
w.URL.revokeObjectURL=url=>revoked.push(url);
w.Image=class {constructor(){this.naturalWidth=4000;this.naturalHeight=3000;images.push(this);}set src(value){this.source=value;}};
w.HTMLCanvasElement.prototype.getContext=()=>({fillRect(){},drawImage(){}});
w.HTMLCanvasElement.prototype.toBlob=function(callback){blobs.push({width:this.width,height:this.height,callback});};
w.photoRecognition={isolateSubject(){const canvas=w.document.createElement('canvas');canvas.width=320;canvas.height=320;return canvas;}};
w.eval(fs.readFileSync('static/photo_trial.js','utf8')+'\nwindow.previewPhoto=previewPhoto;');
const status=()=>w.document.querySelector('#photo-status').textContent;
const hidden=()=>w.document.querySelector('#photo-result').classList.contains('hidden');
const tick=()=>new Promise(resolve=>setImmediate(resolve));
(async()=>{
 await w.previewPhoto({size:21*1024*1024,type:'image/jpeg'});
 assert.match(status(),/20 Mo/);assert.equal(images.length,0);
 await w.previewPhoto({size:10,type:'text/plain'});assert.match(status(),/Choisis une photo/);
 const first=w.previewPhoto({size:100,type:'image/jpeg'});images.at(-1).onload();await tick();
 assert.equal(blobs.at(-1).width,320);assert.equal(blobs.at(-1).height,320);
 blobs.at(-1).callback(new w.Blob(['image']));await first;
 assert.equal(hidden(),false);assert.match(status(),/aucun envoi/i);
 w.document.querySelector('#clear-photo').click();assert.equal(hidden(),true);assert.ok(revoked.length>=2);
 const pending=w.previewPhoto({size:100,type:'image/jpeg'});const stale=images.at(-1);
 w.document.querySelector('#clear-photo').click();stale.onload();await pending;assert.equal(hidden(),true);
 const failed=w.previewPhoto({size:100,type:'image/jpeg'});images.at(-1).onerror();await failed;
 assert.match(status(),/ne peut pas être ouverte/);assert.equal(hidden(),true);
 assert.equal(network,0);dom.window.close();console.log('Photo trial: validation, resize, clear, stale load, decode error, no network passed.');
})().catch(error=>{console.error(error);process.exitCode=1;});
